openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML. or HTML
  version: 1.0


servers:
  - url: http://localhost:8081
    description: Local server
  - url: http://prod.com/
    description: pre-production server
  - url: http://test.com/
    description: production server

